name: agconnect_crash
description: Flutter plugin for AppGallery Connect Crash SDK.
version: 1.9.0+300
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-crash-introduction

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcrash
        pluginClass: AGConnectCrashPlugin
      ios:
        pluginClass: AGConnectCrashPlugin
