name: agconnect_appmessaging_example
description: Demonstrates how to use the agconnect_appmessaging plugin.
version: 1.9.0+300
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13+hotfix.9"

dependencies:
  flutter:
    sdk: flutter
  agconnect_appmessaging:
    path: ../

  cupertino_icons: 1.0.3

dev_dependencies:
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
