name: agconnect_cloudfunctions_example
description: Demonstrates how to use the AppGallery Connect Cloud Functions plugin.
version: 1.3.0+301

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  agconnect_cloudfunctions: 1.6.0+300
#    path: ../agconnect_cloudfunctions

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
