name: agconnect_cloudfunctions
description: AppGallery Connect Cloud Functions plugin for Flutter. Cloud Functions enables serverless computing.
version: 1.9.0+300
homepage: https://developer.huawei.com/consumer/en/agconnect/
repository: https://github.com/AppGalleryConnect/agc-flutter-plugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13+hotfix.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agc.flutter.cloudfunctions
        pluginClass: AGCCloudFunctionsPlugin
      ios:
        pluginClass: AGCCloudFunctionsPlugin
