name: agconnect_crash_example
description: Demonstrates how to use the agconnect_crash plugin.
version: 1.9.0+300

publish_to: "none" 

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_analytics: ^6.5.0+301
  agconnect_crash:
    
    path: ../

  
  cupertino_icons: ^1.0.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter




flutter:
 
  uses-material-design: true

  