name: agconnect_appmessaging
description: You can use App Messaging of AppGallery Connect to send relevant messages to target users.
homepage: https://developer.huawei.com/consumer/en/agconnect/
version: 1.9.0+300

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.12.13+hotfix.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agc.flutter.appmessaging
        pluginClass: AgconnectAppmessagingPlugin
      ios:
        pluginClass: AgconnectAppmessagingPlugin
