name: agconnect_auth_example
description: Demonstrates how to use the agconnect_auth plugin.
version: 1.2.0+300

environment:
  sdk: ">=2.12.0 <4.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: 5.0.7

  huawei_account: 5.2.0+301

  huawei_gameservice: 5.0.4+305

  agconnect_auth:
    path: ../

  cupertino_icons: ^1.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/user-info.json